package com.labdigbdbstgpb.virtual.userInterface;

import net.serenitybdd.screenplay.targets.Target;
import net.thucydides.core.webdriver.shadow.ByShadow;

public class EnviarDineroTagAlfanumericoYCtaAhUI {

    public static final Target TXT_VALOR = Target.the("Ingresr Valor a Enviar").located(ByShadow.cssSelector("#sp-at-input","#root > div > div.shell-container__mf.shell-container__portal > div > div.Bd52\\+oONj5gdhbaHI75R1A\\=\\= > div > div > div > div > div > div > div.aYnul5LM893tB\\+6ygSu7hg\\=\\= > div > div > div.pGVAUG3ECTxqTmhmqlOWdg\\=\\= > div > div.AmlDKyFqPFd62JgAj37juQ\\=\\= > transfers-sp-at-input"));
    public static final Target CTAAHS = Target.the("Seleccionar cuenta de ahorros").located(ByShadow.cssSelector("#check_0 > div > div","#root > div > div.shell-container__mf.shell-container__portal > div > div.Bd52\\+oONj5gdhbaHI75R1A\\=\\= > div > div > div > div > div > div > div.aYnul5LM893tB\\+6ygSu7hg\\=\\= > div > div > div.pGVAUG3ECTxqTmhmqlOWdg\\=\\= > div > div.N85GVkWKf11BB4hf7yyGKQ\\=\\= > div.rnZYBL\\+jp\\+uv\\+NZ6pqBggA\\=\\= > transfers-sp-ml-card-price","#radio__0"));
    public static final Target BTNCONTINUARTAGENVIARDINERO = Target.the("Boton continuar").locatedBy("#root > div > div.shell-container__mf.shell-container__portal > div > div.Bd52\\+oONj5gdhbaHI75R1A\\=\\= > div > div > div > div > div > div > div.aYnul5LM893tB\\+6ygSu7hg\\=\\= > div > div > div.ToOsB9FIHFPPbXTWXLvLBw\\=\\=.aval-key-continue-button-accounts > button");
    public static final Target BTNENVIARDINEROTAG = Target.the("Enviar Dinero").located(ByShadow.cssSelector("#sp-ml-confirmation-button","#root > div > div.shell-container__mf.shell-container__portal > div > div.Bd52\\+oONj5gdhbaHI75R1A\\=\\= > div > div > div > div > div > div > transfers-sp-ml-confirmation"));
    public static final Target BTNOTP = Target.the("Validar OTP").located(ByShadow.cssSelector("#notification-modal-button-0","#miscellaneous-notification-modal-overlay > miscellaneous-bdb-ml-modal","#bdb-ml-modal > miscellaneous-bdb-at-backdrop"));
    public static final Target BTNENVIARCODIGO = Target.the("Enviar OTP").located(ByShadow.cssSelector("div > div.bdb-ml-bm-otp__actions > div.bdb-ml-bm-token__actions__send > button","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-otp"));
    public static final Target CAMPOOTP1 = Target.the("Campo 1").located(ByShadow.cssSelector("#input_0","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target CAMPOOTP2 = Target.the("Campo 2").located(ByShadow.cssSelector("#input_1","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target CAMPOOTP3 = Target.the("Campo 3").located(ByShadow.cssSelector("#input_2","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target CAMPOOTP4 = Target.the("Campo 4").located(ByShadow.cssSelector("#input_3","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target CAMPOOTP5 = Target.the("Campo 5").located(ByShadow.cssSelector("#input_4","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target CAMPOOTP6 = Target.the("Campo 6").located(ByShadow.cssSelector("#input_5","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target BTNVERIFICAR = Target.the("Boton de verificar").located(ByShadow.cssSelector("div > div.bdb-ml-bm-token__actions > div.bdb-ml-bm-token__actions__send > button","#two-factor-authentication-overlay > div > div.sherpa-grid > div > div > div > miscellaneous-bdb-ml-bm-token","#inputs > miscellaneous-bdb-at-input-token"));
    public static final Target MSJTRXEXITOSA = Target.the("Envio Exisotos").located(ByShadow.cssSelector("#sp-ml-bm-voucher > div > div.voucher__header > div:nth-child(1) > div.voucher__header__title > div","#voucher > div.Bd52\\+oONj5gdhbaHI75R1A\\=\\= > div > div > div > div > div.SDo6Zm93p0uspgu3xCPJ0Q\\=\\= > transfers-sp-ml-bm-voucher"));
}
